name: Keep DNS Supabase Edge Function Warm

# Trigger every 10 minutes and also allow manual trigger
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  warm-up:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -X GET "https://qpenkaurptbxsxrysixw.supabase.co/functions/v1/validate-email"
